# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caseforge < Formula
  desc "AI-powered HTTP API test-case generator from OpenAPI specs"
  homepage "https://github.com/testmind-hq/caseforge"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.7.0/caseforge_0.7.0_darwin_amd64.tar.gz"
      sha256 "0c5c731cfc1feeb1df5746fe2e888fdfa4767463312a749e0861e47d5353300c"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.7.0/caseforge_0.7.0_darwin_arm64.tar.gz"
      sha256 "f8e5498645bc7426e0718be5e451c6722937c89d61f0f2a77d3f63ad9518be75"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.7.0/caseforge_0.7.0_linux_amd64.tar.gz"
      sha256 "25603b031751c751332fb4a50cac1b52f3c998b0550373aeb02df33913caa2dc"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.7.0/caseforge_0.7.0_linux_arm64.tar.gz"
      sha256 "1fef6e1f2ad1c72f7946748794c0fee282b271fea6b869395ad868bff4f9af56"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  test do
    system "#{bin}/caseforge", "--version"
  end
end
