# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caseforge < Formula
  desc "AI-powered HTTP API test-case generator from OpenAPI specs"
  homepage "https://github.com/testmind-hq/caseforge"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.9.0/caseforge_0.9.0_darwin_amd64.tar.gz"
      sha256 "ad48bf17a313a15c2a4738b01ede44e1914fa10b8a7a80f44411d9894ee87da4"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.9.0/caseforge_0.9.0_darwin_arm64.tar.gz"
      sha256 "e789d45796062bfd92f498dec9a47ce2a78fafd823ec4753033203a9dafaf655"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.9.0/caseforge_0.9.0_linux_amd64.tar.gz"
      sha256 "b7e273c7b13d383f1a83ef91d88f12ac730a2213491e7d0ccdc3440ef35f6c47"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.9.0/caseforge_0.9.0_linux_arm64.tar.gz"
      sha256 "b4c4be0a9610b4f53a8911a15f7bb1c4354a67a0bde5b7cdb20932bae4a87dc3"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  test do
    system "#{bin}/caseforge", "--version"
  end
end
