# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caseforge < Formula
  desc "AI-powered HTTP API test-case generator from OpenAPI specs"
  homepage "https://github.com/testmind-hq/caseforge"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.10.0/caseforge_0.10.0_darwin_amd64.tar.gz"
      sha256 "982a22a686f7da51130c6eefac5ebc764983b3828c0b510354889d287d76424f"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.10.0/caseforge_0.10.0_darwin_arm64.tar.gz"
      sha256 "e7746bedba66103750b5e8b2b15126c47e05af31ca660f71c57bfbf25d3c7081"

      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.10.0/caseforge_0.10.0_linux_amd64.tar.gz"
      sha256 "b380bb123c9ad915e052fbcb53ce7dae89bcc40a15075e9806898992b1f92b6f"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/testmind-hq/caseforge/releases/download/v0.10.0/caseforge_0.10.0_linux_arm64.tar.gz"
      sha256 "3fc0b30ba451d4328595493352e2e18b9fbd66dd5f1ce17a50b45cc9f6ee280a"
      define_method(:install) do
        bin.install "caseforge"
      end
    end
  end

  test do
    system "#{bin}/caseforge", "--version"
  end
end
